server {
    listen 80;
    server_name welldom05.duckdns.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name welldom05.duckdns.org;

    ssl_certificate     /etc/letsencrypt/live/welldom05.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/welldom05.duckdns.org/privkey.pem;

    client_max_body_size 25M;

    location /api/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /uploads/ {
        proxy_pass http://127.0.0.1:8000;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
